import type { NextPage } from "next"
import Head from 'next/head'
import About from "../view/About/About"
import Qualifications from "../view/Qualifications/Qualifications"
import Projects from "../view/Projects/Projects"
import Contact from "../view/Contact/Contact"
import styles from '../styles/PageStyles/Home.module.css'

const Home: NextPage = () => {
    return (  
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About />
      <Qualifications />
      <Projects />
      <Contact />
    </div>
  )
}

export default Home
